sensor:
  - platform: template
    sensors:
      vacuum_status:
        friendly_name: Estado
        entity_id:
          - vacuum.rockrobo
        value_template: 'Estado: {{ states.vacuum.rockrobo.attributes.status }}'
        icon_template: >
          {% set val =  states.vacuum.rockrobo.attributes.status  %}
          {% if val == 'Charging' %}
            mdi:battery-charging
          {% elif val == 'Cleaning' %}
            mdi:move-resize
          {% elif val == 'Returning home' %}
            mdi:keyboard-return
          {% elif val == 'Idle' %}
            mdi:dots-horizontal
          {% elif val == 'Paused' %}
            mdi:pause-circle
          {% else %}
            mdi:help-circle
          {% endif %}
      vacuum_fan_speed:
        friendly_name: Velocidad ventilador
        entity_id:
          - vacuum.rockrobo
        value_template: 'Modo: {{ states.vacuum.rockrobo.attributes.fan_speed }}'
        icon_template: 'mdi:speedometer'
      vacuum_battery:
        friendly_name: Bateria
        entity_id:
          - vacuum.rockrobo
        value_template: 'Bateria: {{ states.vacuum.rockrobo.attributes.battery_level }}'
        unit_of_measurement: '%'
        icon_template: '{{ states.vacuum.rockrobo.attributes.battery_icon }}'
      vacuum_cleaning_time:
        friendly_name: Ultimo ciclo
        unit_of_measurement: 'min'
        entity_id:
          - vacuum.rockrobo
        value_template: >-
          {% set time = states.vacuum.rockrobo.attributes.last_run_stats.duration %}
          {% set minutes = ((time | int /  60) | string).split('.')[0] %}
          {% set seconds = time | int % 60 %}
          {{minutes}}.{{seconds}}
        icon_template: 'mdi:timer'
      vacuum_cleaned_area:
        friendly_name: Area ultimo ciclo
        unit_of_measurement: 'm ²'
        entity_id:
          - vacuum.rockrobo
        value_template: '{{ states.vacuum.rockrobo.attributes.last_run_stats.area }}'
        icon_template: 'mdi:ruler'
      vacuum_cleanmainbrush:
        friendly_name: Reemplazo cepillo principal
        unit_of_measurement: 'h'
        entity_id:
          - vacuum.rockrobo
        value_template: 'Cepillo principal: {{ states.vacuum.rockrobo.attributes.mainBrush }}'
        icon_template: 'mdi:screwdriver'
      vacuum_cleansidebrush:
        friendly_name: Reemplazo cepillo lateral
        unit_of_measurement: 'h'
        entity_id:
          - vacuum.rockrobo
        value_template: 'Cepillo lateral: {{ states.vacuum.rockrobo.attributes.sideBrush }}'
        icon_template: 'mdi:screwdriver'
      vacuum_cleanfilter:
        friendly_name: Reemplazo filtro
        unit_of_measurement: 'h'
        entity_id:
          - vacuum.rockrobo
        value_template: 'Filtro: {{ states.vacuum.rockrobo.attributes.filter }}'
        icon_template: 'mdi:screwdriver'
      vacuum_sensordirtyleft:
        friendly_name: Limpieza sensores
        unit_of_measurement: 'h'
        entity_id:
          - vacuum.rockrobo
        value_template: 'Sensores: {{ states.vacuum.rockrobo.attributes.sensor }}'
        icon_template: 'mdi:screwdriver'
      vacuum_do_not_disturb:
        friendly_name: No molestar
        entity_id:
          - vacuum.rockrobo
        value_template: '{{ states.vacuum.rockrobo.attributes.do_not_disturb }}'
        icon_template: >
          {% set val =  states.vacuum.rockrobo.attributes.do_not_disturb  %}
          {% if val == 'on' %}
            mdi:do-not-disturb
          {% else %}
            mdi:do-not-disturb-off
          {% endif %} 
      vacuum_cleaner_error_sensor:
        friendly_name: Error
        value_template: >-
          {% if states.vacuum.rockrobo.attributes.state == 'error' %}
            {{states.vacuum.rockrobo.attributes.valetudo_state.name}}
          {% else %}
            No Error
          {% endif %}
